import TextsmsOutlinedIcon from '@mui/icons-material/TextsmsOutlined';
import ImageSearchOutlinedIcon from '@mui/icons-material/ImageSearchOutlined';
import LockOutlinedIcon from '@mui/icons-material/LockOutlined';
import QrCode2OutlinedIcon from '@mui/icons-material/QrCode2Outlined';
import InsertDriveFileOutlinedIcon from '@mui/icons-material/InsertDriveFileOutlined';
import TagOutlinedIcon from '@mui/icons-material/TagOutlined';
import PasswordOutlinedIcon from '@mui/icons-material/PasswordOutlined';
import StickyNote2OutlinedIcon from '@mui/icons-material/StickyNote2Outlined';
import CleaningServicesOutlinedIcon from '@mui/icons-material/CleaningServicesOutlined';
import KeyOutlinedIcon from '@mui/icons-material/KeyOutlined';
import AccountTreeOutlinedIcon from '@mui/icons-material/AccountTreeOutlined';
import PolicyOutlinedIcon from '@mui/icons-material/PolicyOutlined';
import SendOutlinedIcon from '@mui/icons-material/SendOutlined';

export const toolGroups = {
  mvp: {
    label: 'MVP tools',
    description: 'The core workflows Krypt already does best.',
  },
  secondary: {
    label: 'Secondary tools',
    description: 'Practical security helpers that extend the workspace without clutter.',
  },
  labs: {
    label: 'Labs',
    description: 'Experimental workflows for memorable privacy and handoff use cases.',
  },
};

export const tools = [
  {
    slug: 'textToText',
    name: 'Text Encryption',
    group: 'mvp',
    route: '/krypt/textToText',
    detail: 'Fast local workflow',
    accent: '#2f6fed',
    icon: TextsmsOutlinedIcon,
    description: 'Encrypt, decrypt, copy, download, and save text output without storing the key.',
    howToUse: 'Paste text, keep or generate a key, then encrypt or decrypt in the browser.',
    usefulFor: 'Protecting short messages, payloads, and notes before saving them to history.',
    special: 'Krypt stores encrypted output only; keys stay with the user.',
    limitation: 'Educational text encryption, not a replacement for audited enterprise cryptography.',
  },
  {
    slug: 'steganoGraphy',
    name: 'Steganography',
    group: 'mvp',
    route: '/krypt/steganoGraphy',
    detail: 'Image message hiding',
    accent: '#14b8a6',
    icon: ImageSearchOutlinedIcon,
    description: 'Hide messages inside images, recover them later, and save encoded results.',
    howToUse: 'Choose encode or decode, provide an image and passkey, then download the result.',
    usefulFor: 'Low-friction private handoffs where the secret should not look like plain text.',
    special: 'The encoded image remains a normal downloadable image.',
    limitation: 'Steganography hides intent but should still be paired with careful sharing.',
  },
  {
    slug: 'ImageEncryption',
    name: 'Image Encryption',
    group: 'mvp',
    route: '/krypt/ImageEncryption',
    detail: 'File transformation',
    accent: '#c59b32',
    icon: LockOutlinedIcon,
    description: 'Transform image bytes with a key and store only encrypted image output.',
    howToUse: 'Upload an image, enter a key, choose encrypt or decrypt, then download or save.',
    usefulFor: 'Visual demonstrations and quick private image transformations.',
    special: 'Preview and history are built into the same focused workspace.',
    limitation: 'Current image workflow is a demo; File Encryption is stronger for real files.',
  },
  {
    slug: 'qrCode',
    name: 'QR Encryption',
    group: 'mvp',
    route: '/krypt/qrCode',
    detail: 'Shareable payloads',
    accent: '#7c3aed',
    icon: QrCode2OutlinedIcon,
    description: 'Generate encrypted QR payloads for compact protected sharing demos.',
    howToUse: 'Enter a message and secret key, generate a QR, or paste a payload to decrypt.',
    usefulFor: 'Short offline handoffs where scanning is easier than copying ciphertext.',
    special: 'Uses AES-based QR payloads with a simple decode path.',
    limitation: 'QR capacity is limited; use Secure Handoff for larger payloads.',
  },
  {
    slug: 'fileEncryption',
    name: 'File Encryption',
    group: 'secondary',
    route: '/krypt/fileEncryption',
    detail: 'AES-GCM package',
    accent: '#0f766e',
    icon: InsertDriveFileOutlinedIcon,
    description: 'Encrypt or decrypt any file into a portable .krypt package.',
    howToUse: 'Select a file, enter a passphrase, download the encrypted package, or import one to decrypt.',
    usefulFor: 'Protecting documents, archives, and media before sending or storing them.',
    special: 'Uses Web Crypto AES-GCM with PBKDF2-derived keys and no server upload.',
    limitation: 'Large files are processed in-memory in this MVP.',
  },
  {
    slug: 'hashVerifier',
    name: 'Hash Verifier',
    group: 'secondary',
    route: '/krypt/hashVerifier',
    detail: 'Integrity checks',
    accent: '#2563eb',
    icon: TagOutlinedIcon,
    description: 'Generate SHA hashes for text or files and compare expected values.',
    howToUse: 'Paste text or choose a file, select SHA-256/384/512, and optionally compare a known hash.',
    usefulFor: 'Checking downloads, verifying copied content, and confirming file integrity.',
    special: 'Works entirely in the browser with instant match/mismatch feedback.',
    limitation: 'Hashing proves integrity, not secrecy.',
  },
  {
    slug: 'passwordGenerator',
    name: 'Password Generator',
    group: 'secondary',
    route: '/krypt/passwordGenerator',
    detail: 'Crypto random',
    accent: '#0891b2',
    icon: PasswordOutlinedIcon,
    description: 'Generate strong passwords and memorable passphrases with useful controls.',
    howToUse: 'Pick password or passphrase mode, adjust controls, generate, and copy.',
    usefulFor: 'Creating safer secrets for accounts, handoffs, and encryption keys.',
    special: 'Uses browser crypto randomness rather than Math.random.',
    limitation: 'Krypt does not store or recover generated passwords.',
  },
  {
    slug: 'secureNotes',
    name: 'Secure Notes',
    group: 'secondary',
    route: '/krypt/secureNotes',
    detail: 'Encrypted notes',
    accent: '#16a34a',
    icon: StickyNote2OutlinedIcon,
    description: 'Encrypt notes locally and save only ciphertext to your Krypt history.',
    howToUse: 'Write a note, choose a passphrase, save encrypted, then decrypt later with the same passphrase.',
    usefulFor: 'Private snippets, recovery hints, and sensitive reminders.',
    special: 'The backend receives ciphertext and metadata only.',
    limitation: 'If the passphrase is lost, Krypt cannot recover the note.',
  },
  {
    slug: 'metadataCleaner',
    name: 'Metadata Cleaner',
    group: 'secondary',
    route: '/krypt/metadataCleaner',
    detail: 'Image privacy',
    accent: '#64748b',
    icon: CleaningServicesOutlinedIcon,
    description: 'Re-encode images to strip embedded metadata before sharing.',
    howToUse: 'Upload an image, preview file details, clean it, then download the re-encoded copy.',
    usefulFor: 'Reducing accidental leaks from screenshots and photos.',
    special: 'Creates a simple privacy receipt explaining what was removed.',
    limitation: 'MVP supports image metadata cleanup only.',
  },
  {
    slug: 'keyDerivation',
    name: 'Key Derivation Preview',
    group: 'secondary',
    route: '/krypt/keyDerivation',
    detail: 'PBKDF2 lab',
    accent: '#ca8a04',
    icon: KeyOutlinedIcon,
    description: 'See how a passphrase becomes a derived key with salt and iterations.',
    howToUse: 'Enter a passphrase, salt, and iteration count, then derive a preview key.',
    usefulFor: 'Learning why key derivation protects weak passphrases.',
    special: 'Shows timing, algorithm, and derived material in one receipt.',
    limitation: 'Educational preview; do not paste production secrets.',
  },
  {
    slug: 'secretSplitter',
    name: 'Secret Splitter',
    group: 'labs',
    route: '/krypt/secretSplitter',
    detail: 'Threshold sharing',
    accent: '#9333ea',
    icon: AccountTreeOutlinedIcon,
    description: 'Split a secret into shares where only a chosen threshold can recover it.',
    howToUse: 'Enter a secret, choose total shares and threshold, then distribute the generated shares.',
    usefulFor: 'Emergency access, team recovery, and offline custody workflows.',
    special: 'A memorable advanced workflow uncommon in ordinary encryption sites.',
    limitation: 'Shares must be stored separately; anyone with enough shares can reconstruct.',
  },
  {
    slug: 'privacyScanner',
    name: 'Privacy Risk Scanner',
    group: 'labs',
    route: '/krypt/privacyScanner',
    detail: 'Leak detection',
    accent: '#dc2626',
    icon: PolicyOutlinedIcon,
    description: 'Scan text for emails, phone numbers, URLs, tokens, and other risky patterns.',
    howToUse: 'Paste text or filenames, run the scan, then review highlighted risk categories.',
    usefulFor: 'Checking messages, logs, and notes before sharing them.',
    special: 'Turns Krypt into a privacy advisor, not just a converter.',
    limitation: 'Pattern-based scanner; it can miss context-specific secrets.',
  },
  {
    slug: 'secureHandoff',
    name: 'Secure Handoff',
    group: 'labs',
    route: '/krypt/secureHandoff',
    detail: 'Package + QR',
    accent: '#ea580c',
    icon: SendOutlinedIcon,
    description: 'Create an encrypted handoff package for a message or small payload.',
    howToUse: 'Write a message, choose a passphrase, generate a package, and share it with instructions.',
    usefulFor: 'One-off private delivery without exposing plaintext in chat or email.',
    special: 'Combines encrypted package, compact QR preview, and a plain-language receipt.',
    limitation: 'Recipient still needs the passphrase through a separate channel.',
  },
];

export const mvpTools = tools.filter((tool) => tool.group === 'mvp');
export const secondaryTools = tools.filter((tool) => tool.group === 'secondary');
export const labTools = tools.filter((tool) => tool.group === 'labs');
export const getToolBySlug = (slug) => tools.find((tool) => tool.slug === slug);
